# Generated by Django 4.0.6 on 2023-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Domain')),
                ('sentence_L1', models.CharField(blank=True, max_length=1000, null=True)),
                ('sentence_L2', models.CharField(blank=True, max_length=1000, null=True)),
                ('score', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Score ')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remark ')),
                ('typee', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Type ')),
            ],
        ),
    ]
