# Generated by Django 4.0.6 on 2023-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dataset_sentence_l3'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssameseBodoDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Domain')),
                ('sentence_L1', models.CharField(blank=True, max_length=1000, null=True)),
                ('sentence_L2', models.CharField(blank=True, max_length=1000, null=True)),
                ('score', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Score ')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remark ')),
                ('typee', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Type ')),
            ],
        ),
        migrations.CreateModel(
            name='AssameseEnglishDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Domain')),
                ('sentence_L1', models.CharField(blank=True, max_length=1000, null=True)),
                ('sentence_L3', models.CharField(blank=True, max_length=1000, null=True)),
                ('score', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Score ')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remark ')),
                ('typee', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Type ')),
            ],
        ),
        migrations.CreateModel(
            name='BodoEnglishDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Domain')),
                ('sentence_L2', models.CharField(blank=True, max_length=1000, null=True)),
                ('sentence_L3', models.CharField(blank=True, max_length=1000, null=True)),
                ('score', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Score ')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remark ')),
                ('typee', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Type ')),
            ],
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
