# Generated by Django 4.0.6 on 2023-06-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_assameseenglishdataset_dataset_lang_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assameseenglishdataset',
            old_name='sentence_L3',
            new_name='sentence_L2',
        ),
        migrations.RenameField(
            model_name='bodoenglishdataset',
            old_name='sentence_L3',
            new_name='sentence_L1',
        ),
    ]
